Remove random stuff not in scope of this script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,31 +1,4 @@
 #!/bin/bash
-#
-# Script: setup
-#
-# Author: Gabriel Luchina
-# https://luchina.com.br
-#
-# COPYRIGHT - 2021, 2022
-# 
-# All rights reserved - You may not copy, reproduce, distribute, publish, display, perform, modify, 
-# create derivative works, transmit, or in any way exploit any such content, nor may you distribute 
-# any part of this content over any network, including a local area network, sell or offer it for 
-# sale, or use such content to construct any kind of database. 
-# 
-# You may not alter or remove any copyright or other notice from copies of the content on any scripts 
-# in the solution of 'OSX-PROXMOX Solution - GABRIEL LUCHINA'. 
-#
-# Copying or storing any content except as provided above is expressly prohibited without prior 
-# written permission of copyright holder identified in the individual content’s copyright notice. 
-# 
-# For permission to use the content 'OSX-PROXMOX Solution - GABRIEL LUCHINA', 
-# please contact legal@luchina.com.br
-# 
-# FOR DEV/STUDENT ONLY PURPOSES - NOT COMERCIAL
-#
-# Credits:
-# https://github.com/acidanthera/OpenCorePkg
-# https://github.com/corpnewt/MountEFI
 
 ################################################################################################################################################################################################
 ################################################################################################################################################################################################
@@ -36,7 +9,7 @@ clear
 if [ `pveversion | grep "pve-manager/[7,8]" | wc -l` -ne 1 ]
 then
 	echo "This version of Proxmox Virtual Environment are not supported"
-	echo "Please, utilize version: 7.XX or 8.2"
+	echo "Please, utilize version: 7.XX or 8.XX"
 	exit
 fi
 
@@ -80,23 +53,18 @@ then
 
 	cp ${SCRIPT_DIR}/EFI/*.iso /var/lib/vz/template/iso
 
-	echo "alias osx-setup='${SCRIPT_DIR}/setup'" >> /root/.bashrc
+	# echo "alias osx-setup='${SCRIPT_DIR}/setup'" >> /root/.bashrc
 
-	echo -e "LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8" > /etc/environment
-	echo "set mouse-=a" > ~/.vimrc
+	# echo -e "LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8" > /etc/environment
+	# echo "set mouse-=a" > ~/.vimrc
 
-	if [ -e /etc/apt/sources.list.d/pve-enterprise.list ]; then rm -rf /etc/apt/sources.list.d/pve-enterprise.list; fi;
+	# if [ -e /etc/apt/sources.list.d/pve-enterprise.list ]; then rm -rf /etc/apt/sources.list.d/pve-enterprise.list; fi;
 
 	apt-get update > ${LOGFILE} 2>> ${LOGFILE}
 
 	if [ $? -ne 0 ]
 	then 
-		echo "Error with 'apt-get update' ..."
-		echo "Trying to change /etc/apt/sources.list"
-
-		sed -i 's/ftp.br.debian.org/ftp.debian.org/g' /etc/apt/sources.list
-		
-		echo "Retrying 'apt-get update'"
+		echo "Error with 'apt-get update'. Retrying ..."
 		apt-get update >> ${LOGFILE} 2>> ${LOGFILE}
 		if [ $? -ne 0 ]; then echo "Error with `apt-get update ...`"; exit; fi
 	fi
@@ -104,37 +72,35 @@ then
 	apt install vim unzip zip sysstat parted wget iptraf git htop -y >> ${LOGFILE} 2>> ${LOGFILE}
 	if [ $? -ne 0 ]; then echo "Error with `apt-get install ...`"; exit; fi
 
-	sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
+	# sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
 
-	if [ ${OSX_PLATFORM} == "AMD" ]
-	then
-		if [ `pveversion | grep -i '7.2\|7.3\|7.4\|8.0\|8.1\|8.2' | wc -l` -eq 1 ]
-		then
-			sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt video=vesafb:off video=efifb:off initcall_blacklist=sysfb_init"/g' /etc/default/grub
-		else
-			sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt video=vesafb:off video=efifb:off"/g' /etc/default/grub
-		fi
-		echo "options kvm-amd nested=1" > /etc/modprobe.d/kvm-amd.conf
-	fi
+	# if [ ${OSX_PLATFORM} == "AMD" ]
+	# then
+	# 	if [ `pveversion | grep -i '7.2\|7.3\|7.4\|8.0\|8.1\|8.2' | wc -l` -eq 1 ]
+	# 	then
+	# 		sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt video=vesafb:off video=efifb:off initcall_blacklist=sysfb_init"/g' /etc/default/grub
+	# 	else
+	# 		sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt video=vesafb:off video=efifb:off"/g' /etc/default/grub
+	# 	fi
+	# 	echo "options kvm-amd nested=1" > /etc/modprobe.d/kvm-amd.conf
+	# fi
 
-	if [ ${OSX_PLATFORM} == "INTEL" ]
-	then
-		if [ `pveversion | grep -i '7.2\|7.3\|7.4\|8.0\|8.1\|8.2' | wc -l` -eq 1 ]
-		then
-			sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt video=vesafb:off video=efifb:off initcall_blacklist=sysfb_init"/g' /etc/default/grub
-		else
-			sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt video=vesafb:off video=efifb:off"/g' /etc/default/grub
-		fi
-		echo "options kvm-intel nested=Y" > /etc/modprobe.d/kvm-intel.conf
-	fi
+	# if [ ${OSX_PLATFORM} == "INTEL" ]
+	# then
+	# 	if [ `pveversion | grep -i '7.2\|7.3\|7.4\|8.0\|8.1\|8.2' | wc -l` -eq 1 ]
+	# 	then
+	# 		sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt video=vesafb:off video=efifb:off initcall_blacklist=sysfb_init"/g' /etc/default/grub
+	# 	else
+	# 		sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt video=vesafb:off video=efifb:off"/g' /etc/default/grub
+	# 	fi
+	# 	echo "options kvm-intel nested=Y" > /etc/modprobe.d/kvm-intel.conf
+	# fi
 
-	echo -e "vfio\nvfio_iommu_type1\nvfio_pci\nvfio_virqfd\n" >> /etc/modules
-	echo -e "blacklist nouveau\nblacklist nvidia\nblacklist snd_hda_codec_hdmi\nblacklist snd_hda_intel\nblacklist snd_hda_codec\nblacklist snd_hda_core\nblacklist radeon\nblacklist amdgpu\n" >> /etc/modprobe.d/pve-blacklist.conf
+	# echo -e "vfio\nvfio_iommu_type1\nvfio_pci\nvfio_virqfd\n" >> /etc/modules
+	# echo -e "blacklist nouveau\nblacklist nvidia\nblacklist snd_hda_codec_hdmi\nblacklist snd_hda_intel\nblacklist snd_hda_codec\nblacklist snd_hda_core\nblacklist radeon\nblacklist amdgpu\n" >> /etc/modprobe.d/pve-blacklist.conf
 
-	echo "options kvm ignore_msrs=Y report_ignored_msrs=0" > /etc/modprobe.d/kvm.conf
-	echo "options vfio_iommu_type1 allow_unsafe_interrupts=1" > /etc/modprobe.d/iommu_unsafe_interrupts.conf
-
-	sed -i.backup -z "s/res === null || res === undefined || \!res || res\n\t\t\t.data.status.toLowerCase() \!== 'active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
+	# echo "options kvm ignore_msrs=Y report_ignored_msrs=0" > /etc/modprobe.d/kvm.conf
+	# echo "options vfio_iommu_type1 allow_unsafe_interrupts=1" > /etc/modprobe.d/iommu_unsafe_interrupts.conf
 
 	touch /etc/pve/qemu-server/.osx-proxmox
 
@@ -144,11 +110,11 @@ then
 	echo " "
 	echo "... Successfully completed prerequisite process, your HOST will restart within 15s."
 	echo " "
-	echo "After rebooting, RUN: osx-setup"
+	# echo "After rebooting, RUN: osx-setup"
 	echo " "
 	echo " "
 
-	sleep 15s && reboot
+	# sleep 15s && reboot
 
 fi
 
@@ -1539,34 +1505,34 @@ do
 	if [ ${OPT} -eq 200 ]
 	then
 
-		clear
+		# clear
 
-		LOGFILE=${LOGDIR}/add-repo-pve-no-subscription.log
+		# LOGFILE=${LOGDIR}/add-repo-pve-no-subscription.log
 
-		echo " "
-		echo "Adding 'Promox VE NO Subscription repository' ..."
-		echo " "
-		echo "Please wait ..."
-		echo " "
+		# echo " "
+		# echo "Adding 'Promox VE NO Subscription repository' ..."
+		# echo " "
+		# echo "Please wait ..."
+		# echo " "
 
-		if [ `pveversion | grep "pve-manager/[7]" | wc -l` -ne 1 ]
-		then
-			echo "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription" > /etc/apt/sources.list.d/pxve-no-sub.list
-			apt update -y >> ${LOGFILE} 2>> ${LOGFILE}
-			if [ $? -ne 0 ]; then echo "apt update error - check log file ${LOGFILE}"; exit; fi;
-			echo "Promox VE NO Subscription repository has been successfully added."	
-			exit
-		fi
+		# if [ `pveversion | grep "pve-manager/[7]" | wc -l` -ne 1 ]
+		# then
+		# 	echo "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription" > /etc/apt/sources.list.d/pxve-no-sub.list
+		# 	apt update -y >> ${LOGFILE} 2>> ${LOGFILE}
+		# 	if [ $? -ne 0 ]; then echo "apt update error - check log file ${LOGFILE}"; exit; fi;
+		# 	echo "Promox VE NO Subscription repository has been successfully added."	
+		# 	exit
+		# fi
 
-		if [ `pveversion | grep "pve-manager/[8]" | wc -l` -ne 1 ]
-		then
-			echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pxve-no-sub.list
-			apt update -y >> ${LOGFILE} 2>> ${LOGFILE}
-			if [ $? -ne 0 ]; then echo "apt update error - check log file ${LOGFILE}"; exit; fi;
-			echo "Promox VE NO Subscription repository has been successfully added."	
-			exit
-		fi
-
+		# if [ `pveversion | grep "pve-manager/[8]" | wc -l` -ne 1 ]
+		# then
+		# 	echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pxve-no-sub.list
+		# 	apt update -y >> ${LOGFILE} 2>> ${LOGFILE}
+		# 	if [ $? -ne 0 ]; then echo "apt update error - check log file ${LOGFILE}"; exit; fi;
+		# 	echo "Promox VE NO Subscription repository has been successfully added."	
+		# 	exit
+		# fi
+		exit
 	fi
 
 ################################################################################################################################################################################################
@@ -1610,16 +1576,16 @@ do
 
 		clear
 
-		echo " "
-		echo "Clearing all macOS Recovery Images in '/var/lib/vz/template/iso'"
-		echo " "
+		# echo " "
+		# echo "Clearing all macOS Recovery Images in '/var/lib/vz/template/iso'"
+		# echo " "
 
-		rm -f /var/lib/vz/template/iso/recovery-*.iso
-		rm -f ${LOGDIR}/crt-recovery-*.log
+		# rm -f /var/lib/vz/template/iso/recovery-*.iso
+		# rm -f ${LOGDIR}/crt-recovery-*.log
 
-		echo "Please wait ..."
-		echo "Clear of ALL macOS Recovery Images completed!"
-		echo " "
+		# echo "Please wait ..."
+		# echo "Clear of ALL macOS Recovery Images completed!"
+		# echo " "
 
 		exit
 
@@ -1640,15 +1606,15 @@ do
 
 		clear
 
-		echo " "
-		echo "Removing Proxmox Subscription Notice..."
-		echo " "
+		# echo " "
+		# echo "Removing Proxmox Subscription Notice..."
+		# echo " "
 
-		sed -i.backup -z "s/res === null || res === undefined || \!res || res\n\t\t\t.data.status.toLowerCase() \!== 'active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js && systemctl restart pveproxy.service
+		# sed -i.backup -z "s/res === null || res === undefined || \!res || res\n\t\t\t.data.status.toLowerCase() \!== 'active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js && systemctl restart pveproxy.service
 
-		echo "Please wait ..."
-		echo "Remove of Proxmox Subscription Notice completed!"
-		echo " "
+		# echo "Please wait ..."
+		# echo "Remove of Proxmox Subscription Notice completed!"
+		# echo " "
 
 		exit
 
@@ -1669,54 +1635,54 @@ do
 
 		clear
 
-		LOGFILE=${LOGDIR}/activate-macOS-in-cloud-vultr.log
+		# LOGFILE=${LOGDIR}/activate-macOS-in-cloud-vultr.log
 
-		echo " "
-		echo "Enabling macOS in Cloud (VultR Provider)"
-		echo " "
-		echo "Please wait ..."
-		echo " "
+		# echo " "
+		# echo "Enabling macOS in Cloud (VultR Provider)"
+		# echo " "
+		# echo "Please wait ..."
+		# echo " "
 
-		echo -e "\n## Interface for VMs \nauto vmbr1
-		iface vmbr1 inet static
-		        address  192.168.1.1
-		        netmask  255.255.255.0
-		        bridge_ports none
-		        bridge_stp off
-		        bridge_fd 0
-		\n        
-		post-up echo 1 > /proc/sys/net/ipv4/ip_forward
-		post-up   iptables -t nat -A POSTROUTING -s '192.168.1.0/24' -o vmbr0 -j MASQUERADE
-		post-down iptables -t nat -D POSTROUTING -s '192.168.1.0/24' -o vmbr0 -j MASQUERADE" >> /etc/network/interfaces
+		# echo -e "\n## Interface for VMs \nauto vmbr1
+		# iface vmbr1 inet static
+		#         address  192.168.1.1
+		#         netmask  255.255.255.0
+		#         bridge_ports none
+		#         bridge_stp off
+		#         bridge_fd 0
+		# \n        
+		# post-up echo 1 > /proc/sys/net/ipv4/ip_forward
+		# post-up   iptables -t nat -A POSTROUTING -s '192.168.1.0/24' -o vmbr0 -j MASQUERADE
+		# post-down iptables -t nat -D POSTROUTING -s '192.168.1.0/24' -o vmbr0 -j MASQUERADE" >> /etc/network/interfaces
 
-		ifup vmbr1 >> ${LOGFILE} 2>> ${LOGFILE}
+		# ifup vmbr1 >> ${LOGFILE} 2>> ${LOGFILE}
 
-		apt -y update >> ${LOGFILE} 2>> ${LOGFILE}
-		apt -y install sysstat net-tools isc-dhcp-server >> ${LOGFILE} 2>> ${LOGFILE}
+		# apt -y update >> ${LOGFILE} 2>> ${LOGFILE}
+		# apt -y install sysstat net-tools isc-dhcp-server >> ${LOGFILE} 2>> ${LOGFILE}
 
-		sed -i 's/INTERFACESv4=""/INTERFACESv4="vmbr1"/g' /etc/default/isc-dhcp-server
+		# sed -i 's/INTERFACESv4=""/INTERFACESv4="vmbr1"/g' /etc/default/isc-dhcp-server
 
-		cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.backup
+		# cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.backup
 
-		echo 'subnet 192.168.1.0 netmask 255.255.255.0 {
-		  range 192.168.1.10 192.168.1.100;
-		  option routers 192.168.1.1;
-		  option subnet-mask 255.255.255.0;
-		  default-lease-time 600;
-		  max-lease-time 7200;
-		  ddns-update-style none;
-		  authoritative;
-		  option domain-name-servers 8.8.8.8,8.8.4.4;
-		  option domain-name "local";
-		}' > /etc/dhcp/dhcpd.conf
+		# echo 'subnet 192.168.1.0 netmask 255.255.255.0 {
+		#   range 192.168.1.10 192.168.1.100;
+		#   option routers 192.168.1.1;
+		#   option subnet-mask 255.255.255.0;
+		#   default-lease-time 600;
+		#   max-lease-time 7200;
+		#   ddns-update-style none;
+		#   authoritative;
+		#   option domain-name-servers 8.8.8.8,8.8.4.4;
+		#   option domain-name "local";
+		# }' > /etc/dhcp/dhcpd.conf
 
-		echo " "
-		echo "Enable of macOS in Cloud (VultR Provider) completed!"
-		echo " "
-		echo "Your server are reboot in 5s"
+		# echo " "
+		# echo "Enable of macOS in Cloud (VultR Provider) completed!"
+		# echo " "
+		# echo "Your server are reboot in 5s"
 
-		sleep 5s && reboot
-
+		# sleep 5s && reboot
+		exit
 	fi
 
 ################################################################################################################################################################################################
